update appmetrica_plugin (appmetrica 1.x not works with new projects; need to recheck KSCrash dependency build error: demangle.h:19:10: fatal error: 'absl/base/config.h' file not found)
This reverts commit b1a545bc5a6da5745e7ccb0b59c09f7be0b0d553.